In [10]:
import numpy as np

# numpy arrays are mutable
a = np.array([1, 2, 3])
a[0] = 5
print(a)

# print first element
print(a[0])
# print first element using negative index
print(a[-3])

[5 2 3]
5
5


In [11]:
# update an element of a 2D array
b = np.array([[1, 2, 3], [4, 5, 6]])
b[0, 0] = 7
print(b)

[[7 2 3]
 [4 5 6]]


In [12]:
# example of using axis 0 and 1
c = np.array([[1, 2, 3], [4, 5, 6]])
print(c.sum(axis=0))  # sum of each column
print(c.sum(axis=1))  # sum of each row

[5 7 9]
[ 6 15]


In [13]:
# create a 1D array and delete the first and the last element
e = np.array([1, 2, 3, 4, 5])
e = np.delete(e, [0, 4])
print(e)

[2 3 4]


In [14]:
# example of using axis 0 and 1 for deleting
d = np.array([[1, 2, 3], [4, 5, 6]])
print(np.delete(d, 0, axis=0))  # delete first row
print(np.delete(d, 0, axis=1))  # delete first column

[[4 5 6]]
[[2 3]
 [5 6]]


In [15]:
# example of appending an element to a 1D array
f = np.array([1, 2, 3])
f = np.append(f, 4)
print(f)

[1 2 3 4]


In [16]:
# example of using axis 0 and 1 for appending
g = np.array([[1, 2, 3], [4, 5, 6]])
print(np.append(g, [[7, 8, 9]], axis=0))  # append a row
print(np.append(g, [[7], [8]], axis=1))  # append a column

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3 7]
 [4 5 6 8]]


In [17]:
# example of inserting an element to a 1D array
h = np.array([1, 2, 3])
h = np.insert(h, 1, 4)
print(h)

[1 4 2 3]


In [18]:
# example of using axis 0 and 1 for inserting
i = np.array([[1, 2, 3], [4, 5, 6]])
print(np.insert(i, 1, [7, 8, 9], axis=0))  # insert a row
print(np.insert(i, 1, 7, axis=1))  # insert a column

[[1 2 3]
 [7 8 9]
 [4 5 6]]
[[1 7 2 3]
 [4 7 5 6]]


In [19]:
# example of using axis 0 and 1 for stacking
j = np.array([1, 2, 3])
k = np.array([4, 5, 6])
print(np.stack((j, k), axis=0))  # stack arrays vertically
print(np.stack((j, k), axis=1))  # stack arrays horizontally


[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
