# Slicing arrays

In [1]:
import numpy as np
a = np.arange(20).reshape(4,5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [6]:
# slice items starting from row 1 to 4 and from column 2 to 5
print(a[1:4, 2:5])
# equivalent to the previous example
print(a[1:, 2:])
# slice items of the third column and copy it to a new variable
new_vector = a[:, 2].copy()
print(new_vector)

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]
[[ 7  8  9]
 [12 13 14]
 [17 18 19]]
[ 2  7 12 17]


In [10]:
# create a 2D array and extract the diagonal
a = np.array([[11, 12, 13], [21, 22, 23], [31, 32, 33]])
print(a)
print(a.diagonal())
# extract the diagonal one above the main diagonal
print(a.diagonal(offset=1))
# using the diag method
print(np.diag(a, k=1))

[[11 12 13]
 [21 22 23]
 [31 32 33]]
[11 22 33]
[12 23]
[12 23]


In [11]:
# create a 2D array and extract the unique values
a = np.array([[1, 2, 3], [4, 5, 6], [1, 2, 3]])
print(a)
print(np.unique(a))

[[1 2 3]
 [4 5 6]
 [1 2 3]]
[1 2 3 4 5 6]
