# Boolean Indexing, Set Operations, and Sorting

In [2]:
# 2D array of 5x5 elements. Use boolean indexing to select elements
import numpy as np
arr = np.arange(25).reshape(5,5)
print(arr)
print(arr[(arr > 10) & (arr < 17)])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[11 12 13 14 15 16]


In [3]:
# create 3 1D arrays and find the intersection, the union and the difference of the arrays
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([5,6,7,8,9])
print(np.intersect1d(arr1, arr2))
print(np.union1d(arr1, arr2))
print(np.setdiff1d(arr1, arr2))


[5]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4]


In [5]:
# create an unsorted 1d array of 10 integers elements using rand and then sort it
arr = np.random.randint(1, 100, 10)
print(arr)
print(np.sort(arr))


[10 56  8 43 56 44 53 70 60 86]
[ 8 10 43 44 53 56 56 60 70 86]


In [8]:
# example of a 2d array with 3 rows and 3 columns and sort the rows and columns
arr = np.array([[9,8,7],[6,5,4],[3,2,1]])
print(arr)

print(np.sort(arr, axis=0))
print(np.sort(arr, axis=1))

[[9 8 7]
 [6 5 4]
 [3 2 1]]
[[3 2 1]
 [6 5 4]
 [9 8 7]]
[[7 8 9]
 [4 5 6]
 [1 2 3]]


Create a 5 x 5 ndarray X with consecutive integers from 1 to 25 (inclusive). Afterwards use Boolean indexing to pick out only the odd numbers in the array and assign the result to Y.

In [10]:
import numpy as np

# Create a 5 x 5 ndarray with consecutive integers from 1 to 25 (inclusive).
X = np.arange(1, 26).reshape(5, 5)
print(X)
# Use Boolean indexing to pick out only the odd numbers in the array
Y = X[X % 2 != 0]
print(Y)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[ 1  3  5  7  9 11 13 15 17 19 21 23 25]
