# Arithmetic operations and broadcasting

In [2]:
import numpy as np

# create 2 1d arrays and add them together
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = a + b
print(c)
# using the add function
c = np.add(a, b)
print(c)

[5 7 9]
[5 7 9]


In [3]:
# example of subtracting 2 arrays
c = a - b
print(c)
# using the subtract function
c = np.subtract(a, b)
print(c)

[-3 -3 -3]
[-3 -3 -3]


In [4]:
# example of multiplying 2 arrays
c = a * b
print(c)
# using the multiply function
c = np.multiply(a, b)
print(c)

[ 4 10 18]
[ 4 10 18]


In [5]:
# example of dividing 2 arrays
c = a / b
print(c)
# using the divide function
c = np.divide(a, b)
print(c)

[0.25 0.4  0.5 ]
[0.25 0.4  0.5 ]


In [6]:
# example of squaring a 2d array
a = np.array([[1, 2], [3, 4]])
c = a**2
print(c)
# using the power function
c = np.power(a, 2)
print(c)
# exp and sqrt functions are also available

[[ 1  4]
 [ 9 16]]
[[ 1  4]
 [ 9 16]]


In [9]:
# example of the average of a 2d array
a = np.array([[1, 2], [3, 4]])
print(a)
c = np.mean(a)
print(c)
# average of each column
c = np.mean(a, axis=0)
print(c)
# average of each row
c = np.mean(a, axis=1)
print(c)

[[1 2]
 [3 4]]
2.5
[2. 3.]
[1.5 3.5]


In [11]:
# calculate the standard deviation of a 2d array
a = np.array([[1, 2], [3, 4]])
print(a)
c = np.std(a)
print(c)
# the median
c = np.median(a)
print(c)
# the max and the min
c = np.max(a)
print(c)
c = np.min(a)
print(c)
# the sum
c = np.sum(a)
print(c)


[[1 2]
 [3 4]]
1.118033988749895
2.5
4
1
10


In [12]:
# example of addition of one 2d array to one 1d array (broadcasting)
a = np.array([[1, 2], [3, 4]])
b = np.array([5, 6])
c = a + b
print(c)

[[ 6  8]
 [ 8 10]]


In [13]:
# Use Broadcasting to create a 4 x 4 ndarray that has its first column full of `1`s, its second column full of `2`s, its third column full of `3`s, etc..
X = np.ones((4, 4)) * np.array([1, 2, 3, 4])
print(X)


[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]
